package model

import (
	"time"

	"github.com/google/uuid"

	"github.com/wearegravitylabs/silo/api/pkg/currency"
)

// CashFlowType indicates whether money came in or went out.
type CashFlowType string

const (
	CashFlowIn  CashFlowType = "cash_in"
	CashFlowOut CashFlowType = "cash_out"
)

// CashFlowCategory is the reason for a cash movement on an asset.
// Typed so the compiler catches invalid category strings at call sites.
type CashFlowCategory string

// Cash-in categories — income generated by an asset.
const (
	CategoryRentalIncome CashFlowCategory = "rental_income"
	CategoryDividend     CashFlowCategory = "dividend"
	CategoryInterest     CashFlowCategory = "interest"
	CategoryDistribution CashFlowCategory = "distribution"  // VC payout / fund distribution
	CategorySaleProceeds CashFlowCategory = "sale_proceeds"
	CategoryOtherIncome  CashFlowCategory = "other_income"
)

// Cash-out categories — expenses related to an asset.
const (
	CategoryMaintenance   CashFlowCategory = "maintenance"
	CategoryRepair        CashFlowCategory = "repair"
	CategoryInsurance     CashFlowCategory = "insurance"
	CategoryPropertyTax   CashFlowCategory = "property_tax"
	CategoryManagementFee CashFlowCategory = "management_fee"
	CategoryRenewal       CashFlowCategory = "renewal" // domain / subscription renewals
	CategoryOtherExpense  CashFlowCategory = "other_expense"
)

// AssetCashFlow records a single income or expense event for an asset.
// The initial cost basis is captured by asset_lots, not here.
type AssetCashFlow struct {
	ID       uuid.UUID        `gorm:"type:uuid;primary_key;default:uuid_generate_v4()" json:"id"`
	AssetID  uuid.UUID        `gorm:"type:uuid;not null;index"                         json:"asset_id"`
	FlowType CashFlowType     `gorm:"not null"                                         json:"flow_type"`
	Category CashFlowCategory `gorm:"not null"                                         json:"category"`
	Amount   float64          `gorm:"type:numeric(28,10);not null"                     json:"amount"`
	// Currency is the ISO 4217 code for the amount (e.g. "USD").
	Currency  currency.Code `gorm:"not null;default:'USD'" json:"currency"`
	FlowDate  time.Time     `gorm:"type:date;not null"     json:"flow_date"`
	Notes     string        `json:"notes"`
	CreatedAt time.Time     `json:"created_at"`
}

// CreateCashFlowRequest is the payload for POST /assets/:id/cash-flows.
type CreateCashFlowRequest struct {
	FlowType CashFlowType     `json:"flow_type" binding:"required,oneof=cash_in cash_out"`
	Category CashFlowCategory `json:"category"  binding:"required"`
	Amount   float64          `json:"amount"    binding:"required,gt=0"`
	// Currency defaults to the asset's currency when omitted.
	Currency currency.Code `json:"currency"`
	FlowDate time.Time     `json:"flow_date" binding:"required"`
	Notes    string        `json:"notes"`
}
