package model

import (
	"time"

	"github.com/google/uuid"
)

// CashFlowType indicates whether money came in or went out.
type CashFlowType string

const (
	CashFlowIn  CashFlowType = "cash_in"
	CashFlowOut CashFlowType = "cash_out"
)

// Cash-in categories — income generated by an asset.
const (
	CategoryRentalIncome  = "rental_income"
	CategoryDividend      = "dividend"
	CategoryInterest      = "interest"
	CategoryDistribution  = "distribution"  // VC payout / fund distribution
	CategorySaleProceeds  = "sale_proceeds"
	CategoryOtherIncome   = "other_income"
)

// Cash-out categories — expenses related to an asset.
const (
	CategoryMaintenance   = "maintenance"
	CategoryRepair        = "repair"
	CategoryInsurance     = "insurance"
	CategoryPropertyTax   = "property_tax"
	CategoryManagementFee = "management_fee"
	CategoryRenewal       = "renewal"       // domain / subscription renewals
	CategoryOtherExpense  = "other_expense"
)

// AssetCashFlow records a single income or expense event for an asset.
// The initial cost basis is captured by asset_lots, not here.
type AssetCashFlow struct {
	ID       uuid.UUID    `gorm:"type:uuid;primary_key;default:uuid_generate_v4()" json:"id"`
	AssetID  uuid.UUID    `gorm:"type:uuid;not null;index"                         json:"asset_id"`
	FlowType CashFlowType `gorm:"not null"                                         json:"flow_type"`
	Category string       `gorm:"not null"                                         json:"category"`
	Amount   float64      `gorm:"type:numeric(28,10);not null"                     json:"amount"`
	Currency string       `gorm:"not null;default:'USD'"                           json:"currency"`
	FlowDate time.Time    `gorm:"type:date;not null"                               json:"flow_date"`
	Notes    string       `json:"notes"`
	CreatedAt time.Time   `json:"created_at"`
}

// CreateCashFlowRequest is the payload for POST /assets/:id/cash-flows.
type CreateCashFlowRequest struct {
	FlowType CashFlowType `json:"flow_type" binding:"required,oneof=cash_in cash_out"`
	Category string       `json:"category"  binding:"required"`
	Amount   float64      `json:"amount"    binding:"required,gt=0"`
	// Currency defaults to the asset's currency when omitted.
	Currency string    `json:"currency"`
	FlowDate time.Time `json:"flow_date" binding:"required"`
	Notes    string    `json:"notes"`
}
