/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AuthRouteRouteImport } from './../routes/_auth/route'
import { Route as OnboardingRouteRouteImport } from './../routes/onboarding/route'
import { Route as AuthLoginRouteImport } from './../routes/_auth/login'
import { Route as AuthSignUpRouteImport } from './../routes/_auth/sign-up'
import { Route as AuthVerifyEmailRouteImport } from './../routes/_auth/verify-email'
import { Route as InviteTokenRouteImport } from './../routes/invite.$token'
import { Route as OnboardingIndexRouteImport } from './../routes/onboarding/index'
import { Route as OnboardingInviteRouteImport } from './../routes/onboarding/invite'
import { Route as OnboardingJoinRouteImport } from './../routes/onboarding/join'
import { Route as OnboardingPortfolioRouteImport } from './../routes/onboarding/portfolio'
import { Route as OnboardingProfileRouteImport } from './../routes/onboarding/profile'
import { Route as OnboardingRequestSentRouteImport } from './../routes/onboarding/request-sent'
import { Route as PPortfolioIdRouteRouteImport } from './../routes/p/$portfolioId/route'
import { Route as PPortfolioIdAssetsRouteImport } from './../routes/p/$portfolioId/assets'
import { Route as PPortfolioIdDashboardRouteImport } from './../routes/p/$portfolioId/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingInviteRoute = OnboardingInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingJoinRoute = OnboardingJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingPortfolioRoute = OnboardingPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingRequestSentRoute = OnboardingRequestSentRouteImport.update({
  id: '/request-sent',
  path: '/request-sent',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const PPortfolioIdRouteRoute = PPortfolioIdRouteRouteImport.update({
  id: '/p/$portfolioId',
  path: '/p/$portfolioId',
  getParentRoute: () => rootRouteImport,
} as any)
const PPortfolioIdAssetsRoute = PPortfolioIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PPortfolioIdRouteRoute,
} as any)
const PPortfolioIdDashboardRoute = PPortfolioIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PPortfolioIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/p/$portfolioId': typeof PPortfolioIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/request-sent': typeof OnboardingRequestSentRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/p/$portfolioId/assets': typeof PPortfolioIdAssetsRoute
  '/p/$portfolioId/dashboard': typeof PPortfolioIdDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$portfolioId': typeof PPortfolioIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/request-sent': typeof OnboardingRequestSentRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/p/$portfolioId/assets': typeof PPortfolioIdAssetsRoute
  '/p/$portfolioId/dashboard': typeof PPortfolioIdDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/p/$portfolioId': typeof PPortfolioIdRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/join': typeof OnboardingJoinRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/request-sent': typeof OnboardingRequestSentRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/p/$portfolioId/assets': typeof PPortfolioIdAssetsRoute
  '/p/$portfolioId/dashboard': typeof PPortfolioIdDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/p/$portfolioId'
    | '/login'
    | '/sign-up'
    | '/verify-email'
    | '/invite/$token'
    | '/onboarding/invite'
    | '/onboarding/join'
    | '/onboarding/portfolio'
    | '/onboarding/profile'
    | '/onboarding/request-sent'
    | '/onboarding/'
    | '/p/$portfolioId/assets'
    | '/p/$portfolioId/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$portfolioId'
    | '/login'
    | '/sign-up'
    | '/verify-email'
    | '/invite/$token'
    | '/onboarding/invite'
    | '/onboarding/join'
    | '/onboarding/portfolio'
    | '/onboarding/profile'
    | '/onboarding/request-sent'
    | '/onboarding'
    | '/p/$portfolioId/assets'
    | '/p/$portfolioId/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/onboarding'
    | '/p/$portfolioId'
    | '/_auth/login'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/invite/$token'
    | '/onboarding/invite'
    | '/onboarding/join'
    | '/onboarding/portfolio'
    | '/onboarding/profile'
    | '/onboarding/request-sent'
    | '/onboarding/'
    | '/p/$portfolioId/assets'
    | '/p/$portfolioId/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  PPortfolioIdRouteRoute: typeof PPortfolioIdRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/invite': {
      id: '/onboarding/invite'
      path: '/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof OnboardingInviteRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/join': {
      id: '/onboarding/join'
      path: '/join'
      fullPath: '/onboarding/join'
      preLoaderRoute: typeof OnboardingJoinRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/portfolio': {
      id: '/onboarding/portfolio'
      path: '/portfolio'
      fullPath: '/onboarding/portfolio'
      preLoaderRoute: typeof OnboardingPortfolioRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/request-sent': {
      id: '/onboarding/request-sent'
      path: '/request-sent'
      fullPath: '/onboarding/request-sent'
      preLoaderRoute: typeof OnboardingRequestSentRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/p/$portfolioId': {
      id: '/p/$portfolioId'
      path: '/p/$portfolioId'
      fullPath: '/p/$portfolioId'
      preLoaderRoute: typeof PPortfolioIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$portfolioId/assets': {
      id: '/p/$portfolioId/assets'
      path: '/assets'
      fullPath: '/p/$portfolioId/assets'
      preLoaderRoute: typeof PPortfolioIdAssetsRouteImport
      parentRoute: typeof PPortfolioIdRouteRoute
    }
    '/p/$portfolioId/dashboard': {
      id: '/p/$portfolioId/dashboard'
      path: '/dashboard'
      fullPath: '/p/$portfolioId/dashboard'
      preLoaderRoute: typeof PPortfolioIdDashboardRouteImport
      parentRoute: typeof PPortfolioIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingInviteRoute: typeof OnboardingInviteRoute
  OnboardingJoinRoute: typeof OnboardingJoinRoute
  OnboardingPortfolioRoute: typeof OnboardingPortfolioRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingRequestSentRoute: typeof OnboardingRequestSentRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingInviteRoute: OnboardingInviteRoute,
  OnboardingJoinRoute: OnboardingJoinRoute,
  OnboardingPortfolioRoute: OnboardingPortfolioRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingRequestSentRoute: OnboardingRequestSentRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface PPortfolioIdRouteRouteChildren {
  PPortfolioIdAssetsRoute: typeof PPortfolioIdAssetsRoute
  PPortfolioIdDashboardRoute: typeof PPortfolioIdDashboardRoute
}

const PPortfolioIdRouteRouteChildren: PPortfolioIdRouteRouteChildren = {
  PPortfolioIdAssetsRoute: PPortfolioIdAssetsRoute,
  PPortfolioIdDashboardRoute: PPortfolioIdDashboardRoute,
}

const PPortfolioIdRouteRouteWithChildren =
  PPortfolioIdRouteRoute._addFileChildren(PPortfolioIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  PPortfolioIdRouteRoute: PPortfolioIdRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
