/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AuthRouteImport } from './../routes/_auth'
import { Route as OnboardingRouteRouteImport } from './../routes/onboarding/route'
import { Route as AuthLoginRouteImport } from './../routes/_auth/login'
import { Route as AuthSignupRouteImport } from './../routes/_auth/signup'
import { Route as AuthVerifyEmailRouteImport } from './../routes/_auth/verify-email'
import { Route as OnboardingPortfolioRouteImport } from './../routes/onboarding/portfolio'
import { Route as OnboardingProfileRouteImport } from './../routes/onboarding/profile'
import { Route as PPortfolioIdRouteRouteImport } from './../routes/p/$portfolioId/route'
import { Route as PPortfolioIdAssetsRouteImport } from './../routes/p/$portfolioId/assets'
import { Route as PPortfolioIdDashboardRouteImport } from './../routes/p/$portfolioId/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const OnboardingPortfolioRoute = OnboardingPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const PPortfolioIdRouteRoute = PPortfolioIdRouteRouteImport.update({
  id: '/p/$portfolioId',
  path: '/p/$portfolioId',
  getParentRoute: () => rootRouteImport,
} as any)
const PPortfolioIdAssetsRoute = PPortfolioIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PPortfolioIdRouteRoute,
} as any)
const PPortfolioIdDashboardRoute = PPortfolioIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PPortfolioIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/p/$portfolioId': typeof PPortfolioIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/p/$portfolioId/assets': typeof PPortfolioIdAssetsRoute
  '/p/$portfolioId/dashboard': typeof PPortfolioIdDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/p/$portfolioId': typeof PPortfolioIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/p/$portfolioId/assets': typeof PPortfolioIdAssetsRoute
  '/p/$portfolioId/dashboard': typeof PPortfolioIdDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/p/$portfolioId': typeof PPortfolioIdRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/p/$portfolioId/assets': typeof PPortfolioIdAssetsRoute
  '/p/$portfolioId/dashboard': typeof PPortfolioIdDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/p/$portfolioId'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/onboarding/portfolio'
    | '/onboarding/profile'
    | '/p/$portfolioId/assets'
    | '/p/$portfolioId/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/p/$portfolioId'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/onboarding/portfolio'
    | '/onboarding/profile'
    | '/p/$portfolioId/assets'
    | '/p/$portfolioId/dashboard'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/_auth'
    | '/p/$portfolioId'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/onboarding/portfolio'
    | '/onboarding/profile'
    | '/p/$portfolioId/assets'
    | '/p/$portfolioId/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PPortfolioIdRouteRoute: typeof PPortfolioIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/onboarding/portfolio': {
      id: '/onboarding/portfolio'
      path: '/portfolio'
      fullPath: '/onboarding/portfolio'
      preLoaderRoute: typeof OnboardingPortfolioRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/p/$portfolioId': {
      id: '/p/$portfolioId'
      path: '/p/$portfolioId'
      fullPath: '/p/$portfolioId'
      preLoaderRoute: typeof PPortfolioIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$portfolioId/assets': {
      id: '/p/$portfolioId/assets'
      path: '/assets'
      fullPath: '/p/$portfolioId/assets'
      preLoaderRoute: typeof PPortfolioIdAssetsRouteImport
      parentRoute: typeof PPortfolioIdRouteRoute
    }
    '/p/$portfolioId/dashboard': {
      id: '/p/$portfolioId/dashboard'
      path: '/dashboard'
      fullPath: '/p/$portfolioId/dashboard'
      preLoaderRoute: typeof PPortfolioIdDashboardRouteImport
      parentRoute: typeof PPortfolioIdRouteRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingPortfolioRoute: typeof OnboardingPortfolioRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingPortfolioRoute: OnboardingPortfolioRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PPortfolioIdRouteRouteChildren {
  PPortfolioIdAssetsRoute: typeof PPortfolioIdAssetsRoute
  PPortfolioIdDashboardRoute: typeof PPortfolioIdDashboardRoute
}

const PPortfolioIdRouteRouteChildren: PPortfolioIdRouteRouteChildren = {
  PPortfolioIdAssetsRoute: PPortfolioIdAssetsRoute,
  PPortfolioIdDashboardRoute: PPortfolioIdDashboardRoute,
}

const PPortfolioIdRouteRouteWithChildren =
  PPortfolioIdRouteRoute._addFileChildren(PPortfolioIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PPortfolioIdRouteRoute: PPortfolioIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
