// Package middleware provides Gin HTTP middleware for the Silo API.
package middleware

import (
	"context"
	"net/http"
	"strings"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-contrib/requestid"
	"github.com/gin-gonic/gin"
	"github.com/rs/zerolog"

	apiModel "github.com/wearegravitylabs/silo/api/api/model"
	siloErrors "github.com/wearegravitylabs/silo/api/errors"
	modelEnv "github.com/wearegravitylabs/silo/api/model/env"
	"github.com/wearegravitylabs/silo/api/pkg/contexts"
	"github.com/wearegravitylabs/silo/api/pkg/environment"
	siloJWT "github.com/wearegravitylabs/silo/api/pkg/jwt"
	"github.com/wearegravitylabs/silo/api/pkg/helpers"
	siloLogger "github.com/wearegravitylabs/silo/api/pkg/logger"
)

// serviceName is used in error responses generated by infrastructure-level middleware.
const serviceName = "middleware"

// Middleware holds shared state for all middleware functions.
type Middleware struct {
	env    *environment.Env
	logger zerolog.Logger
}

// New returns a Middleware instance.
func New(env *environment.Env) *Middleware {
	return &Middleware{
		env:    env,
		logger: siloLogger.New(),
	}
}

// CORSMiddleware returns a configured CORS handler.
func (m *Middleware) CORSMiddleware() gin.HandlerFunc {
	allowedOrigins := m.env.GetWithDefault(modelEnv.CORSAllowedOrigins, "http://localhost:3000")
	return cors.New(cors.Config{
		AllowOrigins:     []string{allowedOrigins},
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization", "X-Request-ID"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	})
}

// LoggerMiddleware logs each request with method, path, status, latency, and request ID.
func (m *Middleware) LoggerMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()
		c.Next()

		m.logger.Info().
			Str("method", c.Request.Method).
			Str("path", c.FullPath()).
			Int("status", c.Writer.Status()).
			Dur("latency", time.Since(start)).
			Str("ip", c.ClientIP()).
			Str("request_id", requestid.Get(c)).
			Msg("request")
	}
}

// AuthMiddleware validates the JWT Bearer token and injects the authenticated user ID
// into the request context under contexts.ContextKeyUserID.
// Aborts with 401 when the token is missing or invalid.
func (m *Middleware) AuthMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		authHeader := c.GetHeader("Authorization")
		if authHeader == "" || !strings.HasPrefix(authHeader, "Bearer ") {
			abortUnauthorized(c, siloErrors.ErrUnauthorized)
			return
		}

		tokenStr := strings.TrimPrefix(authHeader, "Bearer ")
		secret := m.env.Get(modelEnv.JWTSigningSecret)

		userID, err := siloJWT.ValidateToken(tokenStr, secret)
		if err != nil {
			abortUnauthorized(c, siloErrors.ErrInvalidToken)
			return
		}

		ctx := context.WithValue(c.Request.Context(), contexts.ContextKeyUserID, userID)
		c.Request = c.Request.WithContext(ctx)
		c.Next()
	}
}

// RequireAuth is the named alias for AuthMiddleware used when declaring protected route groups.
func (m *Middleware) RequireAuth() gin.HandlerFunc {
	return m.AuthMiddleware()
}

// HealthCheck returns a simple liveness probe handler.
func HealthCheck() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.JSON(http.StatusOK, apiModel.APIResponse{
			Code:    http.StatusOK,
			Data:    map[string]string{"service": "silo-api"},
			Message: helpers.StringPtr("ok"),
			Error:   nil,
		})
	}
}

// abortUnauthorized writes a 401 response using the standard error envelope and aborts.
func abortUnauthorized(c *gin.Context, e *siloErrors.TranslatableError) {
	c.AbortWithStatusJSON(http.StatusUnauthorized, apiModel.APIResponse{
		Code:    http.StatusUnauthorized,
		Data:    nil,
		Message: helpers.StringPtr("an error has occurred"),
		Error: &apiModel.ErrorData{
			ID:      requestid.Get(c),
			Service: serviceName,
			Code:    e.Code,
			Message: e.Message,
		},
	})
}
