// Package document implements shared document management for any entity that
// can have file attachments (assets, debts, and any future entity types).
//
// Documents are stored in the private bucket (no public access) and accessed
// exclusively via presigned URLs generated by this service.
package document

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/wearegravitylabs/silo/api/app"
	siloErrors "github.com/wearegravitylabs/silo/api/errors"
	"github.com/wearegravitylabs/silo/api/model"
	siloLogger "github.com/wearegravitylabs/silo/api/pkg/logger"
)

//go:generate mockgen -source document.go -destination ../mock/document/mock_document.go -package document Document

const presignExpiry = 1 * time.Hour

// Document defines document management operations shared across entity types.
type Document interface {
	// UploadToAsset stores a file and attaches it to an asset.
	UploadToAsset(ctx context.Context, assetID, callerID uuid.UUID, portfolioID uuid.UUID, fileName, fileType string, data io.Reader, size int64) (model.AssetDocument, error)
	// UploadToDebt stores a file and attaches it to a debt.
	UploadToDebt(ctx context.Context, debtID, callerID uuid.UUID, portfolioID uuid.UUID, fileName, fileType string, data io.Reader, size int64) (model.AssetDocument, error)
	// ListByAsset returns document metadata for an asset (no URLs).
	ListByAsset(ctx context.Context, assetID uuid.UUID) ([]model.AssetDocument, error)
	// ListByDebt returns document metadata for a debt (no URLs).
	ListByDebt(ctx context.Context, debtID uuid.UUID) ([]model.AssetDocument, error)
	// DownloadURL generates a presigned URL for a document, valid for 1 hour.
	DownloadURL(ctx context.Context, docID uuid.UUID) (model.DocumentDownloadResponse, error)
	// Delete removes the file from storage and soft-deletes the DB record.
	Delete(ctx context.Context, docID uuid.UUID) error
}

type service struct{ dp app.Dependency }

// New returns a Document service.
func New(dp app.Dependency) Document { return &service{dp: dp} }

// UploadToAsset stores a file in the private bucket and attaches it to an asset.
func (s *service) UploadToAsset(ctx context.Context, assetID, callerID uuid.UUID, portfolioID uuid.UUID, fileName, fileType string, data io.Reader, size int64) (model.AssetDocument, error) {
	log := siloLogger.FromCtx(ctx).With().
		Str(siloLogger.LogStrKeyMethod, "document.UploadToAsset").
		Str("asset_id", assetID.String()).
		Logger()

	key := buildKey("assets", portfolioID, assetID, fileName)

	if _, err := s.dp.ObjectStorage.Upload(ctx, s.dp.StoragePrivateBucket, key, data, size); err != nil {
		log.Error().Err(err).Msg("failed to upload document")
		return model.AssetDocument{}, siloErrors.ErrStorageUploadFailed
	}

	doc := model.AssetDocument{
		AssetID:     &assetID,
		PortfolioID: portfolioID,
		FileName:    fileName,
		FileType:    fileType,
		StoragePath: key,
		FileSize:    size,
		UploadedAt:  time.Now().UTC(),
	}
	created, err := s.dp.AssetDocumentStore.CreateDocument(ctx, doc)
	if err != nil {
		log.Error().Err(err).Msg("failed to persist document metadata")
		_ = s.dp.ObjectStorage.Delete(ctx, s.dp.StoragePrivateBucket, key)
		return model.AssetDocument{}, err
	}

	log.Info().Str("doc_id", created.ID.String()).Msg("document uploaded to asset")
	return created, nil
}

// UploadToDebt stores a file in the private bucket and attaches it to a debt.
func (s *service) UploadToDebt(ctx context.Context, debtID, callerID uuid.UUID, portfolioID uuid.UUID, fileName, fileType string, data io.Reader, size int64) (model.AssetDocument, error) {
	log := siloLogger.FromCtx(ctx).With().
		Str(siloLogger.LogStrKeyMethod, "document.UploadToDebt").
		Str("debt_id", debtID.String()).
		Logger()

	key := buildKey("debts", portfolioID, debtID, fileName)

	if _, err := s.dp.ObjectStorage.Upload(ctx, s.dp.StoragePrivateBucket, key, data, size); err != nil {
		log.Error().Err(err).Msg("failed to upload document")
		return model.AssetDocument{}, siloErrors.ErrStorageUploadFailed
	}

	doc := model.AssetDocument{
		DebtID:      &debtID,
		PortfolioID: portfolioID,
		FileName:    fileName,
		FileType:    fileType,
		StoragePath: key,
		FileSize:    size,
		UploadedAt:  time.Now().UTC(),
	}
	created, err := s.dp.AssetDocumentStore.CreateDocument(ctx, doc)
	if err != nil {
		log.Error().Err(err).Msg("failed to persist document metadata")
		_ = s.dp.ObjectStorage.Delete(ctx, s.dp.StoragePrivateBucket, key)
		return model.AssetDocument{}, err
	}

	log.Info().Str("doc_id", created.ID.String()).Msg("document uploaded to debt")
	return created, nil
}

// ListByAsset returns document metadata for an asset.
func (s *service) ListByAsset(ctx context.Context, assetID uuid.UUID) ([]model.AssetDocument, error) {
	return s.dp.AssetDocumentStore.ListByAsset(ctx, assetID)
}

// ListByDebt returns document metadata for a debt.
func (s *service) ListByDebt(ctx context.Context, debtID uuid.UUID) ([]model.AssetDocument, error) {
	return s.dp.AssetDocumentStore.ListByDebt(ctx, debtID)
}

// DownloadURL generates a presigned download URL for the document, valid for 1 hour.
func (s *service) DownloadURL(ctx context.Context, docID uuid.UUID) (model.DocumentDownloadResponse, error) {
	log := siloLogger.FromCtx(ctx).With().
		Str(siloLogger.LogStrKeyMethod, "document.DownloadURL").
		Str("doc_id", docID.String()).
		Logger()

	doc, err := s.dp.AssetDocumentStore.GetDocumentByID(ctx, docID)
	if err != nil {
		log.Error().Err(err).Msg("failed to fetch document")
		return model.DocumentDownloadResponse{}, err
	}

	url, err := s.dp.ObjectStorage.PresignedURL(ctx, s.dp.StoragePrivateBucket, doc.StoragePath, presignExpiry)
	if err != nil {
		log.Error().Err(err).Msg("failed to generate presigned URL")
		return model.DocumentDownloadResponse{}, siloErrors.ErrStorageDownloadFailed
	}

	return model.DocumentDownloadResponse{
		URL:       url,
		ExpiresIn: int(presignExpiry.Seconds()),
	}, nil
}

// Delete removes the file from storage and soft-deletes the DB record.
func (s *service) Delete(ctx context.Context, docID uuid.UUID) error {
	log := siloLogger.FromCtx(ctx).With().
		Str(siloLogger.LogStrKeyMethod, "document.Delete").
		Str("doc_id", docID.String()).
		Logger()

	doc, err := s.dp.AssetDocumentStore.GetDocumentByID(ctx, docID)
	if err != nil {
		log.Error().Err(err).Msg("failed to fetch document for deletion")
		return err
	}

	if err := s.dp.ObjectStorage.Delete(ctx, s.dp.StoragePrivateBucket, doc.StoragePath); err != nil {
		log.Error().Err(err).Msg("failed to delete document from storage")
		return siloErrors.ErrStorageUploadFailed
	}

	if err := s.dp.AssetDocumentStore.SoftDeleteDocument(ctx, docID); err != nil {
		log.Error().Err(err).Msg("failed to soft-delete document record")
		return err
	}

	return nil
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

// buildKey constructs a private storage key: {entityType}/{portfolioID}/{entityID}/{uuid}-{filename}
func buildKey(entityType string, portfolioID, entityID uuid.UUID, fileName string) string {
	safe := strings.NewReplacer("/", "_", "\\", "_", "..", "_").Replace(fileName)
	return fmt.Sprintf("documents/%s/%s/%s/%s-%s",
		entityType, portfolioID.String(), entityID.String(),
		uuid.New().String(), safe)
}
